[project]
name = "gemini-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.10.5",
    "openai>=1.95.1",
    "pytest>=8.4.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
